### ISSUE TITLE
 grafana:latest

### ISSUE THREAD

**Issue by KoenWindey** [alekece/tig-stack#3]
Hi,

I've tried to run this with grafana/grafana:latest or grafana/grafana:6.6.2 in the Dockerfile but get a lot of errors there.

I'm running this on a raspberry pi 4 - any reason why your script falls over?

Regards
Koen

**Comment by alekece** [comment]
@KoenWindey 

Hello,

First thank you for you feedback.
I will investigate to figure out what is going on there. Can you give me the errors (screenshot or simply copy-paste them here). In addition can you give more details about your system environment please ?
