### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mspencerl87** [alekece/tig-stack#4]
Any chance of adding IPMITOOL to be able to scrape devices using IPMI?

**Comment by mspencerl87** [comment]
I'm guessing this can run on the Host instead of container?

**Comment by alekece** [comment]
Hello @mspencerl87 !

I am not sure to fully understand what you want to achieve here because I am not used to IPMITOOL. Can you clarify a bit ? 
Furthermore, feel free to create a PR with the support of IPMI.

**Comment by mspencerl87** [comment]
some of the telegraf inputs allow you to use SNMP and IPMI. This usually requires the use of MIB files for collecting and then outputting. Most of the time it will require you to manually input MIB files and configure the IPMI tool under Linux to achieve this.
But please close the request. I don't think its feasible for this use case.
@alekece 
One can work around this by installing MIBS and IPMI on the docker host if needed i guess.
