### ISSUE TITLE
Later versions of influxdb and grafana?

### ISSUE THREAD

**Issue by martinmalek** [alekece/tig-stack#6]
Hello,

Any thoughts on updating this otherwise very nice stack to later versions of grafana and influxdb?

Best,
Martin

**Comment by alekece** [comment]
Hi @martinmalek,

Sorry for this very late answer. I'll take some time to update the versions in the next few weeks.

**Comment by alekece** [comment]
Actually we previously pinned the versions to avoid breaking changes by using the latest version.

I'll then try to use a newer version but definitely not the latest.
