### ISSUE TITLE
telegraf run.sh permissions

### ISSUE THREAD

**Issue by davemacrae** [alekece/tig-stack#7]
When I run the docker compose up -d command to start up the stack I get a set of permission errors generated by the run.sh script for telegraf.

These are related to the sed command to replace the values and the mount command.

I added a bit of debugging and it appears that the script is being run by the telegraf user.

Bit weird.

Docker Compose version v2.6.0

**Comment by alekece** [comment]
Hi @davemacrae,

Can you give me more context about your execution environment ? For now, this issue never happens on my side.

**Comment by alekece** [comment]
I finally reproduce the bug and just push a fix.
